### PR TITLE
Added system architecture

### LINKED ISSUE #19: System architecture
*Acceptance criteria*
- architecture is documented in `/docs` directory

*Technical notes*
- use markdown
- use google drawing/some other tool for diagrams.

### PR DESCRIPTION
**Pull request by ghostaccount737**
Closes #19

### CODE REVIEW

**Comment by lastlegion** [comment]
Please create a markdown file `docs/architecture.md` and embed the image in that document describing it briefly

**Comment by PVinay737** [comment]
Updated

**Comment by lastlegion** [comment]
Please follow the architecture decision record format for documents
https://adr.github.io/madr/

**Comment by PVinay737** [comment]
Okay

**Review by SapoonDutta — APPROVED** [review]

**Review by SapoonDutta — APPROVED** [review]

**Comment by lastlegion** [comment]
Please add node_modules to gitignore

**Pull request merged**
